# config.yaml
data_source_type: "doc"
chroma_db_path: "parser/tests/output/chroma_db"
chroma_collection: "docs_1768829901"
llm_endpoint: "http://localhost:8000/v1"
llm_model: "gpt-oss"
embedding_endpoint: "http://localhost:8001/v1"
embedding_model: "ruri-embed"
questions_per_chunk: 10
output_dir: "./output"
dataset_name: "my_dataset"
enable_llm_linking: True
embed_with_summary: True
cleanup_temp: False
cleanup_cache: False